### ISSUE TITLE
Provide a separate directive for the default firewall rule

### ISSUE THREAD

**Issue by onnimonni** [UpCloudLtd/upcloud-ansible#11]
The current implementation is that the default firewall rule eg `reject: all` needs to be the last rule in the `upcloud_firewall` directive.

Because of that the last rule is completely different than the other rules and the ansible user needs to apply all sorts of hacks to really get this working.

for example if I run this:
```yml
- debug:
    var: upcloud_firewall_rules

- name: Setup firewalls for the backend groups
  upcloud_firewall:
    state: present
    ip_address: "{{ item }}"
    firewall_rules: "{{ upcloud_firewall_rules }}"
  with_flattened:
    - "{{ groups['db']|default([]) }}"
    - "{{ groups['web']|default([]) }}"
```
Works just fine and outputs this =>
```
 _________________________________
< TASK [upcloud-firewall : debug] >
 ---------------------------------

ok: [localhost] => {
    "upcloud_firewall_rules": [
        {
            "action": "accept",
            "comment": "Member of this cluster",
            "destination_port_end": "22",
            "destination_port_start": "22",
            "direction": "in",
            "family": "IPv4",
            "protocol": "tcp",
            "source_address_end": "94.237.29.230",
            "source_address_start": "94.237.29.230"
        },
        {
            "action": "reject",
            "direction": "in",
            "comment": "Default rule"
        }
    ]
}
______________________________________________________
/ TASK [upcloud-firewall : Setup firewalls for the backend groups ]
 ------------------------------------------------------

changed: [localhost] => (item=example-machine)
```

But If I later on change that machine `94.237.29.230` => `94.237.26.186` and apply these rules again the new machine gets just appended in the back of the list and the default rule isn't last one anymore. So then I'll get this:

![image](https://cloud.githubusercontent.com/assets/5691777/25476841/21c7f21c-2b44-11e7-9c48-b2b781d314cd.png)

Could you please provide better methods for updating the default rule?
